Project2
tongoonamujera/Responsive-Design-MilestoneOne pull request #1
Opened 2021-03-01 11:40 UTC by tongoonamujera

A Project done on media queries such it fits on different screen sizes that is mobile, desktop and tabklet

2021-03-01 18:42 UTC, christianotieno requested changes
## Changes Required ♻️ 
Hello @tongoonamujera 👋 
The project is coming along just fine. We can make it even much better. See my review below 👇 
### Happy coding 💻 
#### Christian Otieno (CR)

2021-03-01 18:42 UTC, christianotieno commented on README.md
> +
## Improve README
- [ ] I would suggest having just one screenshot of the [page in this project'sREADME`. The more we have the more cluttered the documentation looks. Just a nice short explanation explaining the responsiveness would do in this case. What do you think?

2021-03-01 18:42 UTC, christianotieno commented on README.md
> +
## Improve README
- [ ] Can we make these live links like so 👇 ?
```suggestion
Twitter: [@tongomujera](https://twitter.com/tongoonamujera)

GitHub: [@tongoonamujera](https://github.com/tongoonamujera)
```

2021-03-01 18:42 UTC, christianotieno commented on README.md
>  Contributing reviews, issues, and feature requests are welcomed!
## Improve the README 
- [ ] Add instructions on how well to clone and run the project locally.
- [ ] You are also welcomed to use this README [template ](https://github.com/microverseinc/readme-template)to act as inspiration on having a more professional looking `README` file as described [here](https://microverse.zendesk.com/hc/en-us/articles/360055660814-Professional-GitHub-repository).

2021-03-01 18:42 UTC, christianotieno commented on index.html
> +<!DOCTYPE html>
## Improve page layout on large screens 
- We have some elements to take care of in the highlighted sections below have a look
- [ ]  The elements on the page have not been placed as would be expected. We have some unnecessary spacing between the navbar and the three main articles section. The elements in the section below have not been placed as would be expected as well. Hav a look at the comparison below

|[Source Page](https://perma.cc/M5ZV-Q2D6)|[Clone Page](https://raw.githack.com/tongoonamujera/Responsive-Design-MilestoneOne/Project2/index.html)|
|:--:|:--:|
|![tnw](https://user-images.githubusercontent.com/22345961/109542166-c532de00-7ad5-11eb-93f9-bbd0a24dea16.png)|![tnw-clone](https://user-images.githubusercontent.com/22345961/109542195-cebc4600-7ad5-11eb-8769-8f0cd5fe3584.png)|

## Improve layout on small and medium screens
- The changes expected in this breakpoint, mirrors the same ones on the large screen only that we have some additional info to add on this one.
- [ ] Add the `tnw` logo on the page on small and medium screens.
-  [ ] On these small and medium screens, there will be a need to replace the items on the menu in the navbar with the hamburger menu. 
- [ ] Work on the general styling on this section as well. See below the comparisons

|[Source Page](https://perma.cc/M5ZV-Q2D6)|[Clone Page](https://raw.githack.com/tongoonamujera/Responsive-Design-MilestoneOne/Project2/index.html)|
|:--:|:--:|
|![tnw-small-medium](https://user-images.githubusercontent.com/22345961/109542893-ba2c7d80-7ad6-11eb-9fd5-4044867e6367.png)|![tnw-small-medium-clone](https://user-images.githubusercontent.com/22345961/109542913-c0baf500-7ad6-11eb-9b3c-5a556f82411d.png)|

2021-03-01 18:42 UTC, christianotieno commented on style.css
> +}
## Aim to remain `DRY`
- [ ] We do have a repeated rule on line `#1 `and `#44` of this file. Do you mind merging them so as to not appear as repeating yourself?

2021-03-01 18:42 UTC, christianotieno commented on style.css
> +}
## Aim to remain `DRY`
- [ ] We do have a repeated rule on line `#175 `and `#184` of this file. Do you mind merging them so as to not appear as repeating yourself?

2021-03-01 18:42 UTC, christianotieno commented on style.css
> +  }
## Aim to remain `DRY`
- [ ] We do have a repeated rule on line `#349` and `#355` of this file. Do you mind merging them so as to not appear as repeating yourself?

2021-03-01 18:42 UTC, christianotieno commented on style.css
> +  }
## Aim to remain `DRY`
- [ ] We do have a repeated rule on line `#642` and  `#651` of this file. Do you mind merging them so as to not appear as repeating yourself?

2021-03-02 12:32 UTC, MuriloRoque approved these changes
## Status: Approved :green_circle: 

### Hello @tongoonamujera :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2021-03-02 12:36 UTC, merged